# Generated by Django 5.1.6 on 2025-02-18 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Credentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=300, verbose_name='Username')),
                ('password', models.CharField(blank=True, max_length=300, verbose_name='Password')),
            ],
        ),
        migrations.CreateModel(
            name='RemoteJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=400)),
                ('job_type', models.CharField(max_length=500)),
                ('hiring_company', models.CharField(max_length=400)),
                ('location', models.CharField(default='Remote', max_length=200)),
                ('annual_pay', models.CharField(max_length=200)),
                ('eligibility_countries', models.CharField(default='All Countries', max_length=400)),
                ('deadline_date', models.CharField(max_length=50)),
            ],
        ),
    ]
