# Generated by Django 5.1.6 on 2025-02-18 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='credentials',
            options={'verbose_name': 'Credential', 'verbose_name_plural': 'Credentials'},
        ),
        migrations.AlterModelOptions(
            name='remotejob',
            options={'verbose_name': 'Job Listing', 'verbose_name_plural': 'Job Listings'},
        ),
        migrations.AddField(
            model_name='remotejob',
            name='details',
            field=models.TextField(blank=True),
        ),
    ]
